### ISSUE TITLE
elementor meta data in slider

### ISSUE THREAD

**Issue by leschambresdelabarbinais** [elementor/elementor#11517]
bonjour, l'image dans le curseur ne peut pas afficher ses balises alt (elles sont bien
écrites dans la médiathèque), est-ce que quelqu'un peut m'expliquer pourquoi?

Bonjour, les images dans les carrousels Elementor ne peuvent afficher
les balises métas (bien qu'ils soient écrits dans la bibliothèque des
médias), avez-vous des pistes pour régler ça?

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by leschambresdelabarbinais** [comment]
bonjour, l'image dans le curseur ne peut pas afficher ses balises alt (elles sont bien
écrites dans la médiathèque), est-ce que quelqu'un peut m'expliquer pourquoi?

Bonjour, les images dans les carrousels Elementor ne peuvent afficher
les balises métas (bien qu'ils soient écrits dans la bibliothèque des
médias), avez-vous des pistes pour régler ça?

**Comment by leschambresdelabarbinais** [comment]
Est-ce lu ?
