### ISSUE TITLE
✔️ 🚀 Feature Request: This EPIC Tab Widget Update is Needed

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#11773]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Feature Request 1: Able to display Tab Widget content anywhere.

**What problem is your feature request going to solve? Please describe.**

It will allow me to create more advanced Layouts/interfaces.

For example, I'm currently trying to re-create this crypto wallet design through Elementor.

However, I cannot do so because the content inside Tabs are only able to be displayed _below_ the tabs.

See this example: http://prntscr.com/t9zi4e

Notice how the tabs underlined in the red (All, Send, Recent) and the content (marked by the grey square) are not directly above/below each other.

If one could put the content of a Tab inside any section he pleases, amazing things could happen.

One could create a Tab based popup menu where content could be displayed anywhere on the page.

One could create a Crypto wallet that displays completely new data within the same Section by using a Tab based Menu at the top of it.

See here: http://prntscr.com/t9zppo

This would basically enable users to have more Javascript like functionality without actually having to know Javascript.

**Describe the solution you'd like**
Allow content inside Tabs to be put anywhere. (other sections/columns on the page)

========================

Feature Request 2: Ability to put multiple pieces of content under 1 Tab/Have 1 tab control multiple pieces of content.

**What problem is your feature request going to solve? Please describe.**

Building upon the last feature, being able to put multiple pieces of content inside 1 Tab would be ideal.

Imagine this scenario, I'm creating a Crypto Wallet UI like the one here: http://prntscr.com/ta0023

As you can see, when a user selects his wallet type from the drop-down menu, it will change the entire UI to match the coin he selected.

Meaning, it will change the Bitcoin chart section, transaction section, and balance section to that of the newly selected coin.

Currently, a Tab only displays content in 1 area (directly under it).

With this implementation, a single Tab could display multiple templates/shortcodes in multiple areas.

Allowing one to implement the UI above (where one 1 change (the type of wallet selected) makes multiple changes everywhere else).

**Describe the solution you'd like**
Let 1 Tab handle & display MULTIPLE shortcodes/templates, each one able to be put anywhere. 

========================

Feature Request 3: Tab Content Transition Animations

**What problem is your feature request going to solve? Please describe.**

Currently there are no transitions when switching between tabs. 

Being able to have smooth transition animations (especially when the above features are implemented) would be nice.

**Describe the solution you'd like**
Ability to set Animations for data transitions during the switching of Tabs (The content of a Tab should be able to Fade out etc. while switching to the next Tab's content).

========================

Feature Request 4: Able to style 'Before' & 'After' separate from the primary content displayed in Dynamic Tags.

**What problem is your feature request going to solve? Please describe.**

Example: Showing a currency symbol like 'USD' after the user's balance in a smaller font-size and put at the top of the container.

Currently, if I use a Dynamic Tag to insert a shortcode, and I put "$" in the 'Before' section, you cannot style the '$' separately from the shortcode output.

========================

Feature Request 3: Tab Drop-down Menus

**What problem is your feature request going to solve? Please describe.**

If the above functionality is implemented, then easy to create, Tab-based drop-down menus are critically needed.

Imagine 1 using icons like this to display their Tab based drop down menu: http://prntscr.com/ta0edk

Then, they click the menu item and BAM, it displays X content the Tab has been made to display.

Now, imagine having all of the above functionality and not being able to do that...

I rest my case.

**Comment by epoplive** [comment]
No one making a crypto-anything website has any business using wordpress or elementor, good lord.

**Comment by zachkinsey** [comment]
"No one making a crypto-anything website has any business using wordpress or elementor, good lord."

What makes you say that?

Besides potential bad actors via 3rd party plugins/themes, I really don't see too much of an issue running a cloud wallet/exchange through the API of other providers.

75% of vulnerabilities are from WordPress plugins
14% of vulnerabilities are from core WordPress
11% of vulnerabilities are from WordPress themes

Additionally, I don't see a problem with Elementor at all unless you want more functionality like the stuff I listed above.

Speaking of which, I have yet to find any paid add ons that allow such.

The closest I've found is one that can Nest Tabs.

"Imagine how EPICLY rich you'd get since it's so EPIC you can sell it to everyone."

A: Calm down bro, it's not that epic. 

But, it would be pretty epic to do without having to use any custom code (even if it's only 10 lines of javascript) ^_^.

And, I definitely could get quite rich off that actually... lmao.

"Spend $1,000s on a web dev. or years learning front end development yourself. Or, just use this spectacular widget to create the next Coinbase without actually learning all that techie crap!"

"Only 3 easy payments of $997."

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that most of the features requested here were released with Elementor **v3.10**! 🥳 

You can now build more flexible [Nested Tabs](https://elementor.com/help/tabs-widget-2/). This solves the following items:

- [x] **1: Able to display Tab Widget content anywhere.**
- [x] **2: Ability to put multiple pieces of content under 1 Tab/Have 1 tab control multiple pieces of content.**
- [x] **3: Tab Content Transition Animations.**

It's important to note that item "**4: Able to style 'Before' & 'After' separate from the primary content displayed in Dynamic Tags.**" can be done using custom HTML and custom CSS, and we have no plans to add style controls for these fields. In this case, you could do the following:

1. Wrap your text in the `before` fields with a `<span>` tag. Give it a class like so: `<span class="my-before-content">Some text before</span>`.
2. Do the same with your `after` fields: `<span class="my-after-content">Some text after</span>`.
3. Now go to the widget's Advanced tab > Custom CSS and use the classes you added to your content for styling:

````css
selector .my-before-content {
    display: block;
    font-size: 0.75em;
}

selector .my-after-content {
    display: block;
    font-size: 0.75em;
    font-style: italic;
}
````

✔️ Feel free to check it out and update your plugin to the new version!

For the other features, please submit a new [🚀 Feature Request](https://github.com/elementor/elementor/discussions/new?category=feature-request) (one request per thread), and we will consider them if there is not demand from the public.

Thank you so much for your contribution and patience. 🙏 

Cheers 🥂
