### ISSUE TITLE
Missing post meta info styles when Improved CSS Loading experiment enabled (default)

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#17412]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

With the Improved CSS Loading feature enabled, list item bullet points are shown on the front end inside the post meta widget.

The Following CSS seems to be missing when the experiment is enabled:

```
.elementor-widget .elementor-icon-list-items {
    list-style-type: none;
    margin: 0;
}

.elementor-widget .elementor-icon-list-items.elementor-inline-items {
    margin-right: -8px;
    margin-left: -8px;
}
```
## Steps to reproduce

Add a post meta widget to the page. Turn on the experiment, bullet points are added.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.13
	PHP Version: 7.4.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: https://www.example.com/wp
	Home URL: https://www.example.com
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: jamie@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
	Accept Stripe Payments
		Version: 2.0.52
		Author: Tips and Tricks HQ, wptipsntricks

	Category Order and Taxonomy Terms Order
		Version: 1.5.9
		Author: Nsp-Code

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Cookie Notice &amp; Compliance for GDPR / CCPA
		Version: 2.2.1
		Author: Hu-manity.co

	Easy Digital Downloads
		Version: 2.11.4
		Author: Easy Digital Downloads

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	FileBird
		Version: 4.9.8
		Author: Ninja Team

	Google Tag Manager for Wordpress
		Version: 1.14.2
		Author: Thomas Geiger

	JetEngine
		Version: 2.10.3
		Author: Crocoblock

	Post2Pdf
		Version: 1.0.0
		Author: ib3 Limited

	Restrict Content Pro
		Version: 3.5.12
		Author: iThemes

	Restrict Content Pro - Campaign Monitor
		Version: 1.2.3
		Author: iThemes

	Restrict Content Pro - Enforce Strong Passwords
		Version: 1.1.3
		Author: iThemes, LLC

	Restrict Content Pro - Restrict Past Content
		Version: 1.0.3
		Author: Sandhills Development, LLC

	WF RCP Custom Fields
		Version: 1.0.0
		Author: ib3 Limited

	Wordfence Security
		Version: 7.5.7
		Author: Wordfence

	Yoast SEO
		Version: 17.8
		Author: Team Yoast


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive by default


== Log ==
	
Log: showing 20 of 372021-11-18 14:45:02 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-18 14:45:02 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-11-18 14:45:02 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-11-18 14:45:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2021-11-18 14:45:02 [info] elementor-pro::elementor_pro_updater Started 
2021-11-18 14:45:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-11-18 14:45:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-11-18 14:45:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.5.1',
)]
2021-12-01 11:59:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-01 12:00:03 [info] elementor-pro::elementor_pro_updater Started 
2021-12-01 12:00:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-12-01 12:00:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-12-01 12:00:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2022-01-04 10:56:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]
2022-01-04 11:00:02 [info] elementor::elementor_updater Started 
2022-01-04 11:00:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-04 11:00:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-04 11:00:02 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-04 11:00:02 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-04 11:00:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]

PHP: showing 5 of 5PHP: 2021-09-24 12:55:54 [notice X 2][/var/www/vhosts/example.com/releases/38/web/app/plugins/elementor/includes/template-library/sources/local.php::997] Trying to get property &#039;post_type&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-27 17:17:19 [notice X 39][/var/www/vhosts/example.com/releases/42/web/app/plugins/elementor-pro/modules/forms/submissions/actions/save-to-database.php::121] Undefined index: field_label [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-26 10:45:20 [notice X 12][/var/www/vhosts/example.com/releases/47/web/app/plugins/elementor-pro/modules/forms/submissions/actions/save-to-database.php::120] Undefined index: field_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-26 11:18:08 [notice X 529][/var/www/vhosts/example.com/releases/47/web/app/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-18 14:42:28 [notice X 60][/var/www/vhosts/example.com/releases/57/web/app/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


```
</details>

**Comment by jamieburchell** [comment]
@avivu I don't see a v3.6.6 and the issue is still present in the latest v3.6.0?

**Comment by avivu** [comment]
Hello @jamieburchell,
Thank you for noticing. It was mistakenly v3.6.6 instead of v3.6.0.
The latest version is v3.6.1. You can update and view the changes.

Thx!

**Comment by jamieburchell** [comment]
> Hello @jamieburchell, Thank you for noticing. It was mistakenly v3.6.6 instead of v3.6.0. The latest version is v3.6.1. You can update and view the changes.
> 
> Thx!

OK, but you said this was fixed in v3.6.0 but it's still an issue?

**Comment by jamieburchell** [comment]
@avivu Are you able to repro this issue? I don't want to open a support ticket if you are already aware of this and working on a fix.
