### ISSUE TITLE
can access to elementor since add the facebook meta pixel, before that worked

### ISSUE THREAD

**Issue by Baptiste31490** [elementor/elementor#19899]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I can't access anymore to my page with elementor

### Steps to reproduce

Add the meta pixel of facebook
and now i can't access to my elementor page 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.23
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://xn--laboutiquefranaise-lvb.fr
	Home URL: https://xn--laboutiquefranaise-lvb.fr
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: Plain
	Language: fr-FR
	Timezone: 0
	Admin Email: baptiste.couzinie31@outlook.fr
	Debug Mode: Inactive

== Theme ==
	Name: Lusion
	Version: 1.5.7
	Author: AHT
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced AJAX Product Filters for WooCommerce
		Version: 1.6.3.1
		Author: BeRocket

	Arrowpress Core
		Version: 1.0.0
		Author: AHT

	ArrowPress Importer
		Version: 1.2.0
		Author: AHT

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.23
		Author: Facebook

	IONOS Assistant
		Version: 8.3.2
		Author: IONOS

	IONOS Journey
		Version: 1.0.2
		Author: IONOS

	IONOS Performance
		Version: 1.1.2
		Author: IONOS

	Jetpack
		Version: 11.3.2
		Author: Automattic

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	MC4WP: Mailchimp for WordPress
		Version: 4.8.10
		Author: ibericode

	Slider Revolution
		Version: 6.5.15
		Author: ThemePunch

	WooCommerce
		Version: 6.9.3
		Author: Automattic

	WooCommerce Payments
		Version: 4.7.2
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.9.3
		Author: WooCommerce

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	YITH WooCommerce Brands Add-On
		Version: 2.4.0
		Author: YITH

	YITH WooCommerce Compare
		Version: 2.18.0
		Author: YITH

	YITH WooCommerce Quick View
		Version: 1.19.0
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 3.12.0
		Author: YITH

== Must-Use Plugins ==
	1&1 Product Subdomain
		Version: 1.1.0
		Author: 1&1

	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Import Export Website Kit: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut

== Journal ==
	
Log: showing 10 of 102022-09-19 14:38:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-19 14:38:59 [info] elementor::elementor_updater Started 
2022-09-19 14:38:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-19 14:38:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-19 14:38:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-19 14:39:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-23 14:03:57 [info] elementor::elementor_updater Started 
2022-09-23 14:03:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-23 14:03:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-23 14:03:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.9.0-dev1',
)]

PHP: showing 4 of 4PHP: 2022-09-19 15:22:54 [error X 1][/homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/template-library/sources/local.php::864] Uncaught Error: Cannot use object of type WP_Error as array in /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/template-library/sources/local.php:864
Stack trace:
#0 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/template-library/manager.php(476): Elementor\TemplateLibrary\Source_Local->import_template('home-handmade.z...', '/homepages/4/d9...')
#1 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#2 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/template-library/manager.php(575): call_user_func(Array, Array)
#3 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/template-library/manager.php(607): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#4 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#7 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#9 /homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 12:22:08 [warning X 1][/homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 15:25:54 [warning X 6][/homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/modules/landing-pages/module.php::329] Attempt to read property "post_type" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 15:43:43 [warning X 1][/homepages/4/d922392112/htdocs/clickandbuilds/Laboutiquefrancaise/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined array key "wrapper" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-09-20 10:44:45 [error X 4][http://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:20460] Cannot read properties of undefined (reading \'id\') 
JS: 2022-09-20 12:51:35 [error X 8][https://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:767576] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-09-20 12:52:58 [error X 2][https://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.6:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `position_left` value. Expected array or object.',
)]
JS: 2022-09-20 12:52:58 [error X 2][https://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.6:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `position_top` value. Expected array or object.',
)]
JS: 2022-09-20 18:58:12 [error X 1][https://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:571445] Cannot read properties of null (reading \'id\') 
JS: 2022-09-21 12:39:44 [error X 1][http://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.0-dev1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-09-21 15:47:46 [error X 66][http://xn--laboutiquefranaise-lvb.fr/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.0-dev1:2:15625] Cannot read properties of undefined (reading \'global\') 

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there, @Baptiste31490!

Thanks for contacting us.

It seems your issue is related to a conflict with a script you added. You need to check if you added the script correctly and remove it. This issue doesn't happen when the script is added using the recommended methods found [here](https://elementor.com/help/custom-code-pro/), [here](https://elementor.com/academy/how-to-use-elementors-custom-code-feature-pro/), and [here](https://www.wpbeginner.com/wp-tutorials/how-to-properly-add-javascripts-and-styles-in-wordpress/).

Please note that GitHub issues are reserved for bug reports and feature requests, and are not used for support.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.for details.

Regards,

**Comment by Baptiste31490** [comment]
Hello,
It's strange because i didn't have any script, i use the header already in the theme
Can you help me

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nicholaszein** [comment]
> Hello, 
> It's strange because i didn't have any script, i use the header already in the theme 
> Can you help

I'm sorry @Baptiste31490, but I can't provide support through here. Please if you need support contact Elementor Support using one of the channels below:

[Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
[Elementor Knowledge base](https://docs.elementor.com/)
[Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org
[Elementor Developers docs](https://developers.elementor.com/)
If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon. For details.

Best of luck! 😉
