### ISSUE TITLE
Import kit should not serialize already serialized content in post meta

### ISSUE THREAD

**Issue by eriktorsner** [elementor/elementor#21224]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I'm one of the developers of [WP Offload Media](https://deliciousbrains.com/wp-offload-media/). We've seen some support requests from users telling us that their sites break when they are exporting and importing Elementor content using your Import/Export Kit tool. 

When using the Export/Import tools in Elementor, rows from the wp_postmeta table are added to the json output file for each post or page. If the content in  the postmeta `meta_value` column is serialized, the serialized string will be stored as is under the "metadata" key in the JSON file. This is the case for WP Offload Media users. We create a cache key `amazonS3_cache`that contains a serialized array of cached URLs.

Later when this metadata is imported back, the serialized string is passed to the WordPress function `update_meta()` that unfortunately will serialize it again. The string `a:1:{s:3:"foo";s:3:"bar";}`becomes `s:26:"a:1:{s:3:"foo";s:3:"bar";}";`

This can be avoided by adding a call to `maybe_unserialize()` before passing the data to `update_meta()`.

On line 1566 in elementor/core/base/document.php. A naive fix is to change the following:

``` php
if ( ! empty( $data['metadata'] ) ) {
	foreach ( $data['metadata'] as $key => $value ) {
		$this->update_meta( $key, $value );
	}
}
```

into:
```php
if ( ! empty( $data['metadata'] ) ) {
	foreach ( $data['metadata'] as $key => $value ) {
		$value = maybe_unserialize( $value );
		$this->update_meta( $key, $value );
	}
}

```

### Steps to reproduce

1. Deactivate all plugins except Elementor
2. Create and publish a simple page using Elementor, the content doesn't matter
3. In the database, add a row to postmeta for the new page with `meta_key` = "foobar" and `meta_value` = "a:1:{s:3:"foo";s:3:"bar";}". This is to emulate that a 3rd party plugin adds serialized data to posts
4. Create an Export using Elementor >> Tools >> Import/Export Kit, accept all defaults
6. Run the Import Kit tool so that the page is imported back.
7. In the database, check the postmeta for the newly imported page, note that the value for `foobar` is now "s:26:"a:1:{s:3:"foo";s:3:"bar";}";"

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.23.2
	MySQL version: Homebrew v8.0.31
	PHP Version: 8.0.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://www.braindev.local
	Home URL: http://www.braindev.local
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@braindev.local
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-Three
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.10.2
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default

== Log ==
	
JS: showing 1 of 1JS: 2023-02-01 09:59:14 [error X 18][http://www.braindev.local/wp-content/plugins/elementor/assets/js/app.js?ver=3.10.2:3564:33] Cannot read properties of undefined (reading 'remove') 

PHP: showing 2 of 2PHP: 2023-02-02 09:17:25 [warning X 1][/Users/erik.torsner/src/deliciousbrains/braindev/www/dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-02 09:17:28 [notice X 4][/Users/erik.torsner/src/deliciousbrains/braindev/www/dev/wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @eriktorsner! 

Thank you for submitting your issue! 🙏 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards
