### ISSUE TITLE
🐞 Bug Report: Reading progress widget - mobile glitch 

### ISSUE THREAD

**Issue by Barnabas2** [elementor/elementor#22060]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The reading progress widget is flickering on mobile devices, especially when an image runs behind. 

When it goes over text,  you can notice flushes of the text through the reading progress bar. 

I'm on iPhone 13 and the issue is observed both on chrome and safari browsers. 

### Steps to reproduce

I have a horizontal progress bar fixed at the top of the screen on my blog post pages. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.23
	PHP Version: 7.4.15
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /blog/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email:
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.3
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.4
		Author: WP Engine

	Astra Pro
		Version: 4.1.4
		Author: Brainstorm Force

	Book shelf
		Version: 1.0.9
		Author: creativeinteractivemedia

	Bulky - Bulk Edit Products for WooCommerce Premium
		Version: 1.2.2
		Author: VillaTheme

	bunny.net
		Version: 1.0.8
		Author: bunny.net

	Challan Pro
		Version: 4.2.3
		Author: WebAppick

	Convert Pro
		Version: 1.7.5
		Author: Brainstorm Force

	Convert Pro - Addon
		Version: 1.5.5
		Author: Brainstorm Force

	Coreem - Coupon Reminder for WooCommerce
		Version: 2.0.10
		Author: VillaTheme

	CTX Feed Pro
		Version: 6.6.3
		Author: WebAppick Author

	CURCY - WooCommerce Multi Currency Premium
		Version: 2.2.3
		Author: VillaTheme

	DHL Express Commerce
		Version: 3.0.0
		Author: DHL Express

	Download Plugins and Themes from Dashboard
		Version: 1.8.2
		Author: WPFactory

	Dynamic Visibility for Elementor
		Version: 5.0.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	Envato Market
		Version: 2.0.8
		Author: Envato

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.23.0
		Author: FiboSearch Team

	FluentCRM - Marketing Automation For WordPress
		Version: 2.8.0
		Author: WP Email Newsletter Team - FluentCRM

	FluentCRM Pro
		Version: 2.8.0
		Author: Fluent CRM

	Fluent Forms
		Version: 4.3.25
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms Pro Add On Pack
		Version: 4.3.23
		Author: Fluent Forms

	FluentSMTP
		Version: 2.2.4
		Author: FluentSMTP & WPManageNinja Team

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	Instant Indexing
		Version: 1.1.16
		Author: Rank Math

	iThemes Security
		Version: 8.1.5
		Author: iThemes

	Longer Permalinks
		Version: 1.28
		Author: Giannis Economou

	Metorik Helper
		Version: 1.6.2
		Author: Metorik

	Modern Footnotes
		Version: 1.4.16
		Author: Prism Tech Studios

	OneSignal Push Notifications
		Version: 2.4.0
		Author: OneSignal

	Payment Plugins for Stripe WooCommerce
		Version: 3.3.39
		Author: Payment Plugins, support@paymentplugins.com

	Pinterest for WooCommerce
		Version: 1.2.18
		Author: WooCommerce

	Pofily - WooCommerce Product Filters Premium
		Version: 1.1.8
		Author: VillaTheme

	Presto Player
		Version: 1.13.0
		Author: Presto Made, Inc

	Rank Math SEO
		Version: 1.0.111
		Author: Rank Math

	Real3D Flipbook
		Version: 3.36
		Author: creativeinteractivemedia

	Real Cookie Banner
		Version: 3.6.2
		Author: devowl.io

	Real Media Library
		Version: 4.18.36
		Author: devowl.io

	REDIS - WooCommerce Dynamic Pricing and Discounts
		Version: 1.0.10
		Author: VillaTheme

	Sequential Order Numbers for WooCommerce
		Version: 3.5.7.7
		Author: BeRocket

	Smart Slider 3 Pro
		Version: 3.5.1.14
		Author: Nextend

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

	Transglobal Shipping
		Version: 0.0.6
		Author: Transglobal Express

	Ultimate Addons for Elementor
		Version: 1.36.15
		Author: Brainstorm Force

	W3 Total Cache
		Version: 2.3.1
		Author: BoldGrid

	WooCommerce
		Version: 7.6.0
		Author: Automattic

	WooCommerce Abandoned Cart Recovery Premium
		Version: 1.0.11
		Author: VillaTheme

	WooCommerce Cart All in One Premium
		Version: 1.0.11
		Author: VillaTheme

	WooCommerce Checkout Upsell Funnel Premium
		Version: 1.0.7
		Author: VillaTheme

	WooCommerce Email Template Customizer Premium
		Version: 1.1.18
		Author: VillaTheme

	WooCommerce Locations Pack
		Version: 1.9.0
		Author: dangoodman

	WooCommerce Orders Tracking Premium
		Version: 1.1.5
		Author: VillaTheme

	WooCommerce Product Variations Swatches Premium
		Version: 1.0.15
		Author: VillaTheme

	WooCommerce Table Rate Shipping
		Version: 4.3.7
		Author: Bolder Elements

	WooCommerce Thank You Page Customizer Premium
		Version: 1.1.2
		Author: VillaTheme

	WP-PageNavi
		Version: 2.94.0
		Author: Lester 'GaMerZ' Chan

	WPCodeBox
		Version: 2.0.0-beta-2.1
		Author: WPCodeBox

	WP Rocket | WooCommerce Recently Viewed Products Widget Integration
		Version: 
		Author: WP Rocket Support Team

	WP Social Ninja
		Version: 3.9.1
		Author: WPManageNinja LLC

	WP Social Ninja Pro
		Version: 3.9.1
		Author: WPManageNinja LLC

	WP Umbrella
		Version: 2.9.0
		Author: WP Umbrella - Backup & Manage WordPress

== Must-Use Plugins ==
	WP Umbrella
		Version: 1.0.0
		Author: WP Umbrella

	_WPHealthHandlerMU.php
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 1
		container : 2
		heading : 1
		uael-posts : 1
	footer : 2
		container : 16
		icon-box : 2
		icon-list : 2
		image : 4
		text-editor : 2
		uael-ff-styler : 2
	page : 5
		container : 2
		divider : 1
		heading : 1
		post-info : 2
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		uael-ff-styler : 2
	product : 1
		container : 12
		html : 1
		image : 1
		share-buttons : 5
		shortcode : 3
		spacer : 1
		text-editor : 4
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-additional-information : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	section : 30
		container : 13
		heading : 13
		html : 2
		image : 12
		image-box : 6
		shortcode : 4
		tabs : 1
		text-editor : 12
		uael-advanced-heading : 1
		uael-ff-styler : 1
		uael-login-form : 2
		uael-registration-form : 2
		woocommerce-products : 3
	wp-post : 0
		button : 1
		container : 33
		divider : 4
		heading : 12
		image : 5
		shortcode : 7
		tabs : 2
		text-editor : 8
		uael-fancy-heading : 1
		uael-ff-styler : 1
	wp-page : 18
		accordion : 1
		button : 3
		container : 3
		fluent-form-widget : 4
		heading : 9
		html : 1
		icon : 2
		icon-box : 9
		image : 10
		loop-grid : 1
		presto_video : 1
		shortcode : 8
		spacer : 7
		tabs : 1
		text-editor : 15
		uael-advanced-heading : 3
		uael-ff-styler : 2
		uael-modal-popup : 3
		uael-posts : 1
		uael-table-of-contents : 2
	single-post : 1
		author-box : 1
		container : 9
		heading : 1
		html : 1
		post-info : 2
		post-navigation : 1
		progress-tracker : 1
		share-buttons : 5
		shortcode : 1
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 5
		container : 4
		divider : 3
		heading : 2
		post-info : 7
		theme-post-excerpt : 3
		theme-post-featured-image : 3
		theme-post-title : 1

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Editor Top Bar: Inactive by default
	Landing pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Menu: Inactive by default

== Log ==
	
Log: showing 20 of 382023-03-30 13:03:33 [info] elementor::elementor_updater Started 
2023-03-30 13:03:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 13:03:35 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 13:03:35 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 13:03:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 13:03:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-04-02 21:14:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 21:14:14 [info] elementor::elementor_updater Started 
2023-04-02 21:14:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-02 21:14:18 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-02 21:14:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 13:13:24 [info] elementor-pro::elementor_pro_updater Started 
2023-04-06 13:13:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-06 13:13:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-06 13:13:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-10 17:19:11 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 17:19:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 17:19:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 17:19:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 17:19:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]

PHP: showing 3 of 3PHP: 2023-03-16 22:53:55 [notice X 49][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/app/modules/import-export/module.php::629] Trying to get property &#039;label&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-16 22:54:08 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/screenshots/module.php::212] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/screenshots/module.php:212
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/screenshots/module.php(232): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/core/modules-manager.php(87): Elementor\Core\Base\Module::instance()
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/plugin.php(363): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin-&gt;on_elementor_init()
#5 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#6 /opt/bitnami/apps/wordpress/htdocs/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-28 01:44:35 [notice X 7][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::76] Undefined index: form_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-03-28 21:55:20 [error X 2][https://essexmonastery.com/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/editor-dynamic-visibility.js?ver=5.0.4:77:19] dce_model_cid is not defined 

== Elementor - Compatibility Tag ==
	
	CURCY - WooCommerce Multi Currency Premium: Incompatible
	Dynamic Visibility for Elementor: Incompatible
	Elementor Pro: Incompatible
	Pofily - WooCommerce Product Filters Premium: Incompatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Ultimate Addons for Elementor: Compatible

**Comment by Barnabas2** [comment]
Any progress with this? Is the issue replicated by anyone?

**Comment by Barnabas2** [comment]
Latest Elementor update 3.13.0 had this change: `Fix: Wrong ARIA text value in Progress Bar widget` . I'm not sure if it's related to this bug, but the bug it's still not fixed.
