### ISSUE TITLE
core/common/modules/event-tracker/db.php platform cross compatibility bug for INSERT

### ISSUE THREAD

**Issue by SDGPeteBatin** [elementor/elementor#22479]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Line 183 of core/common/modules/event-tracker/db.php

if ( $wpdb->get_var( $query ) !== $this->get_table_name() ) {

Should be changed to 

if ( $wpdb->get_var( $query ) != $this->get_table_name() ) {

Problems arise between different platforms when table prefixes are in use with default installations of MySQL/MariaDB
Unix defines table names as declared and uses case-sensitive comparisons. 
Windows force defines table names in lowercase and uses case-insensitive comparisons.

A stored table prefix of 7a6pcDc in wp-config.php will be stored as 7a6pc**D**c_e_events on Unix but 7a6pc**d**c_e_events on Windows.

Both return the expected result from SHOW TABLES LIKE 7a6pc**D**c_e_events or SHOW TABLES LIKE 7a6pc**d**c_e_events but the comparison on 183 and the use of the not identical operator instead of not equals means that on Windows it will try to execute the CREATE process which will result in error as the table already exists and then another error when it tries to execute ALTER TABLE on line 170.

You could use CREATE TABLE IF NOT EXISTS but this will create/unnecessary extra overhead/resource wastage on every page load.

### Steps to reproduce

Step 1: Install Elementor on Windows that has a mixed case table prefix to install WP and watch the logs.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: mariadb.org binary distribution v10.6.9
	PHP Version: 8.2.6

**Comment by nicholaszein** [comment]
Hello @SDGPeteBatin, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Regards

**Comment by SDGPeteBatin** [comment]
As request.

					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: mariadb.org binary distribution v10.6.9
	PHP Version: 8.2.6
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.xyz.co.uk
	Home URL: https://www.xyz.co.uk
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: xyz@xyz.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.7.2
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.4.9
		Author: WPDeveloper

	FileBird Lite
		Version: 5.3.2
		Author: Ninja Team

	Login No Captcha reCAPTCHA (Google)
		Version: 1.7.1
		Author: Robert Peake and Contributors

	Maintenance
		Version: 4.07
		Author: WebFactory Ltd

	Simple 301 Redirects
		Version: 2.0.7
		Author: WPDeveloper

	Site Kit by Google
		Version: 1.99.0
		Author: Google

	Slider Revolution
		Version: 6.6.13
		Author: ThemePunch

	Super Page Cache for Cloudflare
		Version: 4.7.3
		Author: Optimole

	Yoast SEO
		Version: 20.7
		Author: Team Yoast


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
PHP: showing 1 of 1PHP: 2023-05-18 14:54:05 [notice X 1][D:\inetpub\xyz.co.uk\httpdocs\wp-content\plugins\elementor-pro\modules\custom-css\module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by SDGPeteBatin** [comment]
Status is still Awaiting Feedback, I took the time to supply more feedback.  Again, please let me know if you require more information.

**Comment by SDGPeteBatin** [comment]
@nicholaszein This still has the status of needs feedback.  In 3 months time it will have been a year since I provided the requested information.
