### ISSUE TITLE
❌ 🧩 🐞 Bug Report: Custom Open Graph Meta Description outputs Elementor inline CSS if a Post has an Image Before the Post Content

### ISSUE THREAD

**Issue by koyowe** [elementor/elementor#23368]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a wordpress website with Elementor where organization media personnel can make posts through the wordpress posts menu and load the post in Elementor to edit and publish. I also have custom code that generates meta tags with the post's title, description, image etc as outlined in the Steps to reproduce below.

There's a software update that currently comments out the style CSS associated with images. The comment code gets treated as text instead of proper code for some reason (this is a bug) - so the preview will include the comment code if it's at the top of the post content. So for now I just have to avoid adding images as the first object of a post.

See these two link previews attached, 1st one showing the bug, 2nd one after the post was updated to move the image to the bottom of the post.

![elementor-comment-error - Copy](https://github.com/elementor/elementor/assets/11345671/e2ab39de-c41e-4a96-8ca4-23cd99019a67)

Hopefully you can see it more clearly from the inspector below. 

![elementor-comment-error-inspector](https://github.com/elementor/elementor/assets/11345671/295b5240-5479-4dc7-97b2-3c59020a8573)

So there is this code comment block inside the <style> tag that appears before every image:

```
<style>
/*! elementor - v3.15.0 - 02-08-2023 */
.elementor-widget-text-editor.elementor-drop-cap-view-stacked .elementor-drop-cap{background-color:[#69727d](https://web.facebook.com/hashtag/69727d?__eep__=6&__cft__[0]=AZURYBTlhCSzGUzX13y-dwUvM7lLsdcQPdWlvEOHQutkyUb8a_sPtRfP80CWMUcWVsuKWdqkAeqNmiZbyLk48RkJw3vo5EnMoca98s6tVqp2t4Xs1_Ge0lTfg9u3HPo7sti6NilAK8PYPKDS8N2TKPEX&__tn__=R]-R);color:[#fff](https://web.facebook.com/hashtag/fff?__eep__=6&__cft__[0]=AZURYBTlhCSzGUzX13y-dwUvM7lLsdcQPdWlvEOHQutkyUb8a_sPtRfP80CWMUcWVsuKWdqkAeqNmiZbyLk48RkJw3vo5EnMoca98s6tVqp2t4Xs1_Ge0lTfg9u3HPo7sti6NilAK8PYPKDS8N2TKPEX&__tn__=R]-R)}......
```

What happens is, if you add an image as the first item in a post, the above style is added before the image, and inside the <style> tag is the above comment, and something is wrong with it's syntax, so the wordpress post description excerpt is treating the rest of the CSS as post content. This means the above code can potentially appear in a link preview as was the case here.

I hope the description I've given is clear enough.

### Steps to reproduce

1) Add a new Post using the Elementor editor.

2) Add a new image as the first item.

3) Add post content after the image

4) Create a function named elementor_meta_tags() in the theme's functions.php file and extract the post title and description as shown below to create meta tags:

```
function elementor_meta_tags() {
  global $post;
  //post & page tags
  if (is_singular() && !is_front_page()){
          //get post description
          $postDescription = " ";
          if(is_single()){
	          $postDescription = strip_tags( $post->post_content );
	          $postDescription = strip_shortcodes( $postDescription );
	          $postDescription = str_replace( array("\n", "\r", "\t"), ' ', $postDescription );
	          $postDescription = mb_substr( $postDescription, 0, 300, 'utf8' );
          }
          
          //get post title
          $postTitle = esc_html( get_the_title());
          
          //get post url
          $postURL = get_permalink($post->ID);
          
          echo '
	          <meta property="og:title" content="'.$postTitle.'">
	          <meta property="og:description" content="'.$postDescription.'">
	          <meta property="og:url" content="'.$postURL.'">
	          <meta name="description" content="'.$postDescription.'">
          ';
  }
}
add_action('wp_head', 'elementor_meta_tags');

```
5) Share link to the post on WhatsApp or Facebook and check the link preview

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.52 (Ubuntu) |  
MySQL version: | Ubuntu 22.04 v10.6.12 |  
PHP Version: | 8.1.2-1ubuntu2.13 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment]
Hello @koyowe, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<ins>full, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Best regards

**Comment by nicholaszein** [comment]
Hi @koyowe,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- Since I can't see which plugins and theme you have installed, and also can't know if you are using any type of performance optimization plugin or Elementor Experiment, I can't know if these are affecting in any way how your pages are being rendered, but Elementor will only include inline styles for widgets in a specific situation and if you have the "Improved CSS Loading" feature active. This feature reduced the size of the DOM by only including styles for the widgets you're using in a page once (on the first instance of the widget) inline. This improves performance significantly, but if you don't strip that information correctly from the page content while manipulating it, you will encounter problems. This leads me to the next point:
- Your function is not removing the content correctly. You are using incomplete methods. This is being caused by your custom code, not by Elementor.

After reviewing your custom function, I saw that you forgot to strip all tags. 

### ✅ What you can do to solve your issue:
- Try this revised function instead:

```php

function elementor_meta_tags() {
  global $post;
  //post & page tags
  if (is_singular() && !is_front_page()){
          //get post description
          $postDescription = " ";
          if(is_single()){
	          $postDescription = wp_strip_all_tags( $post->post_content );
	          $postDescription = mb_substr( $postDescription, 0, 300, 'utf8' );
          }
          
          //get post title
          $postTitle = esc_html( get_the_title());
          
          //get post url
          $postURL = get_permalink($post->ID);
          
          echo '
	          <meta property="og:title" content="' . esc_attr( $postTitle ) . '">
	          <meta property="og:description" content="' . esc_attr( $postDescription ) . '">
	          <meta property="og:url" content="' . esc_attr( $postURL ) . '">
	          <meta name="description" content="' . esc_attr( $postDescription ) . '">
          ';
  }
}
add_action('wp_head', 'elementor_meta_tags');

```

I tested this on a fresh installation using only the latest versions of Elementor, Elementor Pro, and the Hello Elementor theme, and it worked as expected.

Don't forget to debug the page URL using the [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/) after applying the changes to re-crawl your posts with the correct information.

Please keep in mind that we are providing this code without any guarantee. Use it at your own risk. Make sure you have backed your site up, and tested on a staging environment first.

### 👍 For now, that's all we can help with. 

----

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<ins>full, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
