### ISSUE TITLE
[🧐 Evaluating] 📚 🧩 🐞 Bug Report: Elementor's implementation of wp_print_media_templates() breaks plugins like Meta Box in WordPress 6.3

### ISSUE THREAD

**Issue by rilwis** [elementor/elementor#23390]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi Elementor team,

In the recent update of WordPress 6.3, I found that the way Elementor calls `wp_print_media_templates()` break the image upload functionality of the [Meta Box](https://metabox.io) plugin. After investigating into the issue, I found some technical things that might interest you:

Meta Box use the `print_media_templates` hook to output its own templates for underscores. This hook is called inside the [`wp_print_media_template()`](https://developer.wordpress.org/reference/functions/wp_print_media_templates/) functions, which is called in `wp_footer` and `admin_footer` actions. This is normal and is the recommended way to output plugin's templates.

However, in the [`app/modules/onboarding/module.php`](https://github.com/elementor/elementor/blob/main/app/modules/onboarding/module.php#L466) file, Elementor call the `wp_print_media_template()` separately at the hook `wp_print_footer_scripts`. Calling it at `wp_print_footer_scripts` seemed to work fine in previous versions of WordPress. However, in WordPress 6.3, if you edit a post with Gutenberg, all the media templates (include the WordPress's media templates) are collected in a JavaScript variable, and are not outputted properly on the page, thus makes the code that uses the template broken.

In the latest version 5.7.4 of Meta Box, we [fixed it](https://github.com/wpmetabox/meta-box/commit/109f748f08f19013acd847165387796a7f82296f) by not outputting media templates with the `print_media_templates` hook. Instead, we use 2 hooks `wp_footer` and `admin_footer` directly. Although it works, but it's not the ideal and logical way to do so.

So, I hope Elementor team can find a better way to call the `wp_print_media_template()` function. I notice that it's called on `onboarding` module, so maybe it's best to check if users are on the onboarding page, and call the function only on that page. The current code calls it everywhere, which might be the root cause of the problem.

### Steps to reproduce

1. Install WordPress 6.3
2. Install Elementor
3. Install Meta Box 5.7.3 from [here](https://wordpress.org/plugins/meta-box/advanced/). The latest version 5.7.4 has a quick fix for that.
4. Create an image_advanced field in Meta Box by adding the following code into your theme's functions.php:

```php
add_filter( 'rwmb_meta_boxes', function ( $meta_boxes ) {
    $meta_boxes[] = [
        'title'      => 'Image test',
        'fields'     => [
            [
                'name' => 'Images',
                'id'   => 'images',
                'type' => 'image_advanced',
            ],
        ],
    ];
    return $meta_boxes;
} );
```

5. Go to edit a post. Normally, there's a "Add Media" button appears in the meta box "Image test". But if Elementor is activated, this button is not visible.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	Site URL: http://mb.test
	Home URL: http://mb.test
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: eStar
	Version: 1.3.6
	Author: GretaThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

== Active Plugins ==
	Elementor
		Version: 3.15.2
		Author: Elementor.com

	Meta Box
		Version: 5.7.5
		Author: MetaBox.io


== Must-Use Plugins ==


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default


== Log ==


== Elementor - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello, @rilwis! 

Thank you for reaching out and raising awareness of this issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by nicholaszein** [comment]
Hello @rilwis!

It seems this issue was solved by the Metabox team. For this reason, I'm locking comments.

Kind regards
