### ISSUE TITLE
⛔ 🐞 Bug Report: Hello Theme Elementor Problem with Meta Description

### ISSUE THREAD

**Issue by AzooraDev** [elementor/elementor#23674]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Hello theme version 2.8.1
Added a new feature that creates a meta description.
This comes into conflict with Yoast and Co.

	function hello_elementor_add_description_meta_tag() {
		$post = get_queried_object();

		if ( is_singular() && ! empty( $post->post_excerpt ) ) {
		echo '<meta name="description" content="' . esc_attr( wp_strip_all_tags( $post->post_excerpt ) ) . '">' . "\n";
		}
	}

This is the result:
<meta name="description" content="xxxx"> 
it´s not good foor SEO

### Steps to reproduce

Update the Theme to the new Versionn 2.8.1

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.12
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://eden-im-web.de
	Home URL: https://eden-im-web.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.66
		Author: Borlabs GmbH

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.9.2
		Author: Wpmet

	Envato Elements
		Version: 2.0.12
		Author: Envato

	eRecht24 legal texts for WordPress
		Version: 3.3.9
		Author: eRecht24, Weslink GmbH

	Evolution Forms
		Version: 23.0818
		Author: MW-ITD GmbH

	Folders
		Version: 2.9.2
		Author: Premio

	GTM4WP
		Version: 1.18.1
		Author: Thomas Geiger

	WP Statistics
		Version: 14.1
		Author: VeronaLabs

	Yoast SEO
		Version: 20.7
		Author: Team Yoast


== Eigenschaften ==
	Custom Fonts: 5
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig deaktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header &amp; Footer: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Global Style Guide: Standardmäßig deaktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert
	Taxonomy Filter: Standardmäßig deaktiviert


== Protokoll ==
	
Log: showing 20 of 432023-04-05 12:51:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 12:51:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-08-28 14:01:09 [info] elementor::elementor_updater Started 
2023-08-28 14:01:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-28 14:01:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-28 14:01:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.13.2',
)]
2023-08-28 14:01:11 [info] elementor-pro::elementor_pro_updater Started 
2023-08-28 14:01:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-28 14:01:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-28 14:01:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.13.1',
)]
2023-09-05 13:06:16 [info] elementor::elementor_updater Started 
2023-09-05 13:06:16 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-05 13:06:16 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-05 13:06:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.15.3',
)]
2023-09-05 13:06:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.15.3',
)]
2023-09-05 13:09:36 [info] elementor-pro::elementor_pro_updater Started 
2023-09-05 13:09:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-05 13:09:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-05 13:09:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.15.1',
)]
2023-09-05 13:09:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.15.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by nicholaszein** [comment]
Hello @AzooraDev,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The Meta Description is enabled by default on the Hello Elementor Theme as requested by users for better SEO. However, if you plan to use a 3rd-party SEO solution, you'll need to remove the Meta Description generated by the Hello Elementor Theme by following the instructions on the documentation here: https://developers.elementor.com/docs/hello-elementor-theme/hello_elementor_add_description_meta_tag/

You can add the code to your Child Theme's `functions.php` file, or use a Code Snippets plugin.

We are working with SEO plugins to find a way to make the compatibility seamless. But for the time being, we don't plan to change this behavior.

### 👍 For now, that's all we can help with. 

Kind regards
