### ISSUE TITLE
 Server Error 500 on Saving/Publishing Elementor Template with Product Meta Widget

### ISSUE THREAD

**Issue by beatpulseapp** [elementor/elementor#24505]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am encountering a critical issue with the Elementor page builder on my website. Whenever I attempt to save or publish a template that includes the Product Meta widget (a core widget of Elementor), I am consistently faced with a Server Error 500. This problem seems to be specifically triggered by the addition of the Product Meta widget, as the error does not occur with other widgets or template elements.

Additional Observations:
1. This issue is consistently reproducible with the Product Meta widget.
2. The error does not appear with other widgets or elements within Elementor.
3. The server and WordPress environment have been checked for compatibility and standard requirements.

Troubleshooting Attempts:
1. I have tried clearing the cache and ensuring that there are no plugin conflicts.
2. The WordPress and Elementor versions are up to date.
3. I have also tested this on different browsers and under different network conditions to rule out client-side issues.

Given the critical nature of this issue, I would greatly appreciate prompt assistance in resolving it. This bug is significantly impacting my ability to manage and update product templates on my website.

Thank you for your attention to this matter.

### Steps to reproduce

1. I start by creating a new template for a single product.
2. I then add the Product Meta widget, which is a standard feature of Elementor.
3. Upon trying to save or publish the template, the process fails.
4. A "Server Error (500 error)" is displayed, preventing any further action.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.22
	PHP Version: 8.1.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://fodda.no
	Home URL: https://fodda.no
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 0
	Admin Email: info@fodda.no
	Debug Mode: Inactive

== Theme ==
	Name: Woodmart Child
	Version: 1.0.0
	Author: XTemos
	Child Theme: Yes
	Parent Theme Name: Woodmart
	Parent Theme Version: 7.3.4
	Parent Theme Author: XTemos

== User ==
	Role: administrator
	WP Profile lang: nb_NO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

== Active Plugins ==
	404 to 301 - Redirect, Log and Notify 404 Errors
		Version: 3.1.4
		Author: Joel James

	Advanced Custom Fields PRO
		Version: 6.2.4
		Author: WP Engine

	Breeze
		Version: 2.0.32
		Author: Cloudways

	Challan Pro
		Version: 4.3.7
		Author: WebAppick

	Checkout with Vipps for WooCommerce
		Version: 1.14.16
		Author: WP Hosting

	Conditional Shipping for WooCommerce
		Version: 3.1.2
		Author: Lauri Karisola / WP Trio

	Easy Auto SKU Generator for WooCommerce
		Version: 1.1.8
		Author: Dan Zakirov

	Elementor
		Version: 3.18.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.0
		Author: Elementor.com

	FluentSMTP
		Version: 2.2.6
		Author: FluentSMTP & WPManageNinja Team

	GPLVault Update Manager
		Version: 5.1.1
		Author: GPL Vault

	Image optimization service by Optimole
		Version: 3.11.2
		Author: Optimole

	Instant Indexing
		Version: 1.1.17
		Author: Rank Math

	Jetpack
		Version: 12.8.1
		Author: Automattic

	Kadence WooCommerce Email Designer
		Version: 1.5.12
		Author: Kadence WP

	Klarna Checkout for WooCommerce
		Version: 2.11.5
		Author: Krokedil

	Klarna On-Site Messaging for WooCommerce
		Version: 1.13.0
		Author: krokedil, klarna

	Klarna Order Management for WooCommerce
		Version: 1.8.3
		Author: klarna, krokedil

	Klarna Payments for WooCommerce
		Version: 3.2.3
		Author: krokedil, klarna, automattic

	Loco Translate
		Version: 2.6.6
		Author: Tim Whitlock

	MonsterInsights - eCommerce Addon
		Version: 8.5.1
		Author: MonsterInsights Team

	MonsterInsights Pro
		Version: 8.22.0
		Author: MonsterInsights

	Performance Lab
		Version: 2.7.0
		Author: WordPress Performance Team

	Product Feed Manager for WooCommerce
		Version: 7.3.19
		Author: RexTheme

	Product Feed Manager for WooCommerce PRO
		Version: 6.4.8
		Author: RexTheme

	Qi Addons For Elementor
		Version: 1.6.6
		Author: Qode Interactive

	Qi Addons For Elementor Premium
		Version: 1.6.2
		Author: Qode Interactive

	Rank Math SEO
		Version: 1.0.207
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.50
		Author: Rank Math

	Safe SVG
		Version: 2.2.2
		Author: 10up

	Sender.net email marketing
		Version: 2.6.0
		Author: Sender

	TaxoPress Pro
		Version: 3.11.1
		Author: TaxoPress

	Theme Editor
		Version: 2.8
		Author: mndpsingh287

	Trustpilot-reviews
		Version: 2.5.925
		Author: Trustpilot

	WebP Express
		Version: 0.25.8
		Author: Bjørn Rosell

	WooCommerce
		Version: 8.3.1
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.7.12
		Author: WooCommerce

	WooCommerce Cost of Goods
		Version: 2.13.0
		Author: SkyVerge

	WooCommerce Print Invoices/Packing Lists
		Version: 3.13.2
		Author: SkyVerge

	WooCommerce Shipment Tracking
		Version: 2.4.1
		Author: WooCommerce

	WooCommerce Table Rate Shipping
		Version: 3.1.6
		Author: WooCommerce

	WooCommerce Weight Based Shipping
		Version: 5.6.3
		Author: weightbasedshipping.com

	Woodmart Core
		Version: 1.0.40
		Author: 

	WPCode Lite
		Version: 2.1.6
		Author: WPCode

	WP File Manager
		Version: 7.2.1
		Author: mndpsingh287

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.20.0
		Author: Rhubarb Group

== Elements Usage ==
	
	container : 1
		container : 23
		heading : 4
		icon : 1
		icon-box : 2
		icon-list : 2
		image : 1
		star-rating : 1
		wd_image_or_svg : 6
		wd_single_product_add_to_cart : 1
		wd_single_product_countdown : 1
		wd_single_product_gallery : 1
		wd_single_product_price : 1
		wd_single_product_short_description : 1
		wd_single_product_stock_progress_bar : 1
		wd_single_product_stock_status : 1
		wd_single_product_title : 1
		wd_wc_hook : 1
	wp-post : 0
		container : 31
		heading : 12
		html : 1
		icon-box : 3
		icon-list : 5
		image : 1
		qi_addons_for_elementor_button : 1
		shortcode : 1
		theme-page-title : 2
		wd_archive_products : 2
		wd_banner : 2
		wd_builder_off_canvas_column_btn : 1
		wd_button : 3
		wd_cart_table : 1
		wd_cart_totals : 1
		wd_checkout_billing_details_form : 1
		wd_checkout_order_review : 1
		wd_checkout_payment_methods : 1
		wd_contact_form_7 : 1
		wd_image_or_svg : 9
		wd_infobox : 3
		wd_infobox_carousel : 1
		wd_popup : 1
		wd_products : 1
		wd_shop_archive_active_filters : 1
		wd_shop_archive_orderby : 2
		wd_shop_archive_view : 1
		wd_sidebar : 1
		wd_single_product_shipping_progress_bar : 1
		wd_social_buttons : 1
		wd_text_block : 20
		wd_title : 8
		wd_wc_breadcrumb : 2
		wd_wc_notices : 3
	wp-page : 9
		container : 19
		heading : 3
		image : 1
		wd_accordion : 2
		wd_banner : 2
		wd_button : 8
		wd_compare : 1
		wd_contact_form_7 : 1
		wd_image_or_svg : 11
		wd_images_gallery : 3
		wd_product_categories : 1
		wd_products : 6
		wd_team_member : 3
		wd_text_block : 14
		wd_title : 18
		wd_video : 1
		wd_wishlist : 1
	loop-item : 1
		container : 2
		heading : 2
		image : 1

== Settings ==
	
	cpt_support: page, woodmart_layout, cms_block, woodmart_slide, portfolio, product
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active
	Build with AI: Inactive by default
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active

== Log ==
	
PHP: showing 13 of 13PHP: 2023-11-08 13:26:18 [notice X 1][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/core/experiments/manager.php::161] preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 14:30:59 [warning X 5][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/core/files/css/base.php::778] Undefined array key "padding_mobile" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 14:32:29 [warning X 1][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 14:35:09 [warning X 2][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/includes/elements/container.php::1847] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 15:17:17 [notice X 100][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 16:06:56 [notice X 217][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::607] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-09 16:50:13 [warning X 5][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-13 02:32:25 [warning X 15][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-11-19 17:07:17 [warning X 30][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor/core/files/css/base.php::778] Undefined array key "background_image_mobile" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-23 13:01:32 [warning X 8][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Undefined array key "pages" [array (
  'trace' => '
#0: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]
PHP: 2023-11-23 13:01:32 [warning X 8][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]
PHP: 2023-12-04 17:24:59 [warning X 1][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1460] Undefined array key "pages" [array (
  'trace' => '
#0: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1460): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1451): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]
PHP: 2023-12-04 17:24:59 [warning X 1][/mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1460] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1460): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1451): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /mnt/data/home/1161678.cloudwaysapps.com/hhauwwqrhp/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]

Log: showing 15 of 152023-11-08 13:52:58 [info] elementor::elementor_updater Started 
2023-11-08 13:52:58 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-08 13:52:58 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-08 13:52:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.2',
  'to' => '3.17.3',
)]
2023-11-08 13:52:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.2',
  'to' => '3.17.3',
)]
2023-12-04 15:55:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-04 15:55:33 [info] elementor::elementor_updater Started 
2023-12-04 15:55:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-04 15:55:35 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-04 15:55:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-04 15:55:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-04 15:58:09 [info] elementor-pro::elementor_pro_updater Started 
2023-12-04 15:58:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-04 15:58:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-04 15:58:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]

JS: showing 10 of 10JS: 2023-11-08 15:08:36 [error X 71][https://woocommerce-1161678-4051645.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:806011] Cannot read properties of undefined (reading 'localized') 
JS: 2023-11-08 15:27:23 [error X 1][https://woocommerce-1161678-4051645.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:312727] Cannot read properties of undefined (reading 'id') 
JS: 2023-11-08 15:30:34 [error X 2][https://woocommerce-1161678-4051645.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading 'dataset') 
JS: 2023-11-08 16:09:38 [error X 4][https://woocommerce-1161678-4051645.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:805504] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-11-08 17:14:13 [error X 1][https://woocommerce-1161678-4051645.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view17666") has already been destroyed and cannot be used. 
JS: 2023-12-03 23:53:34 [error X 1][https://fodda.no/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:32519] jQuery(...).tipsy is not a function 
JS: 2023-12-03 23:53:34 [error X 1][https://fodda.no/wp-admin/load-scripts.php?c=0&loadchunk_0=wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils&ver=6.4.1:7:28760] e.dispatchEvent is not a function 
JS: 2023-12-03 23:59:15 [error X 51][https://fodda.no/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'tools') 
JS: 2023-12-04 02:14:35 [error X 38][https://fodda.no/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28767] undefined is not an object (evaluating 'elementorModules.frontend.tools') 
JS: 2023-12-04 12:03:48 [error X 1][https://fodda.no/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:23755] Cannot read properties of null (reading 'getOptions') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Qi Addons For Elementor: Incompatible
	Qi Addons For Elementor Premium: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Qi Addons For Elementor: Incompatible
	Qi Addons For Elementor Premium: Incompatible
