### ISSUE TITLE
⛔ 🚀 Archive post widget - Badge and Meta Data doesn't have hyperlink

### ISSUE THREAD

**Issue by sriramgroot** [elementor/elementor#28246]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Here we are using the **"Archive Post Widget"** in the Category & Author pages, within that we are not able to have **hyperlinks for Badges(Category & Tags) and Meta Data.**

This would be the best option for customization based on the developer's needs.

![Screenshot 2024-07-30 at 12 35 50 PM](https://github.com/user-attachments/assets/b275f797-f444-45ac-8de3-88dad10729ee)

### Steps to reproduce

1. You can try adding the "Archive Posts" widget from the top left corner
2. Select "Card" skin as a layout.
3. Providing hyperlink/custom URL option was missing

### Expected behavior

We could be able to provide hyperlinks/custom URLs for Badges(Category & Tags) and Meta Data.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: ****
	Home URL: ****
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.4
		Author: WP Engine

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Crisp
		Version: 0.46
		Author: Crisp

	Elementor
		Version: 3.23.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.2
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 9.0.0
		Author: MonsterInsights

	Headers Security Advanced & HSTS WP
		Version: 5.0.36
		Author: 🐙 Andrea Ferro

	Microsoft Clarity
		Version: 0.9.4
		Author: Microsoft

	Security Optimizer
		Version: 1.5.1
		Author: SiteGround

	Speed Optimizer
		Version: 7.6.2
		Author: SiteGround

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.1
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing Pages: Inactive by default
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
JS: showing 6 of 6JS: 2024-07-16 12:23:51 [error X 2][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:25:2187] The specified "childViewContainer" was not found: > .e-con-inner 
JS: 2024-07-16 12:34:56 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:831949] Cannot read properties of undefined (reading 'localized') 
JS: 2024-07-16 13:07:45 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:831442] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-07-17 10:17:45 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:329987] Cannot read properties of undefined (reading 'id') 
JS: 2024-07-25 13:22:28 [error X 2][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.23.1:3:51852] c[0] is undefined 
JS: 2024-07-26 10:04:07 [error X 1][../wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.23.3:2:30732] elementor.settings.page is undefined 

PHP: showing 4 of 4PHP: 2024-07-16 13:11:18 [notice X 14][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-24 11:41:28 [notice X 26][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-24 14:14:56 [notice X 116][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-29 12:16:11 [notice X 48][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 202024-07-25 13:34:07 [info] elementor::elementor_updater Started 
2024-07-25 13:34:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-25 13:34:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-25 13:34:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-25 13:34:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-25 13:38:02 [info] elementor-pro::elementor_pro_updater Started 
2024-07-25 13:38:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-25 13:38:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-25 13:38:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-25 13:38:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-26 05:39:21 [info] elementor::elementor_updater Started 
2024-07-26 05:39:21 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-26 05:39:21 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-26 05:39:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-26 05:39:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-30 06:54:37 [info] elementor-pro::elementor_pro_updater Started 
2024-07-30 06:54:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-30 06:54:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-30 06:54:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-30 06:54:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @sriramgroot!

Thank you for reaching out! 🙏 

Unfortunately, what you are reporting here is not a bug. It's just a feature not supported in the Archive Posts widget. This is something we cannot change due to Backward Compatibility.

This is why we created the [Loop Builder](https://elementor.com/help/loop-grid/), so users can create their own Loop Item templates, with all the Dynamic Data they want using the available widgets like the Post Info, and Dynamic Tags. We suggest you switch to using the Loop Grid widget, build your layout, and add the available fields. This way you have more control over the information you want to display, and dynamic content in general. For archive templates use the **`Current Query`** as the query source, and making sure the number of posts per page is the same as set in your WordPress **`Dashboard`** > **`Settings`** > **`Reading`** page. This will ensure the pagination works correctly. Plus, the Loop Grid widget has way more controls and design options.

Just to clarify, Elementor GitHub issues are reserved for reporting Bugs in the code of Elementor or Elementor Pro, or malfunctioning features. Missing options does not fall in this category. In this case, [submitting a Feature Request](https://elemn.to/gh-feature-requests) is more appropriate. I hope you can understand.

I'm closing this issue as it's not a bug.

Kind regards
