### ISSUE TITLE
Missing custom meta keys in dynamic settings

### ISSUE THREAD

**Issue by cenemil** [elementor/elementor#7789]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
It seems like there is a bug in the latest version of Elementor plugin. The post custom field keys are missing(works last week) when setting dynamic data(button, heading, links or any other widget). However, the existing meta data are still connected to the settings and works in the front-end but there is no way to add or change the meta keys since there are no options at all. Attached file shows the missing key.

Elementor Version 2.5.11
Elementor Pro Version 2.5.4

## Steps to reproduce
- Register a custom post type(recipe or store, etc)
- Register a meta box(Wordpress meta) for the post type above
- Create an elementor template and fill it with heading or any other widget that supports dynamic data setup(content)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```				
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.42-84.2
	PHP Version: 7.3.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 60M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://www.pokolbinestate.jezweb.sydney
	Home URL: http://www.pokolbinestate.jezweb.sydney
	WP Multisite: No
	Max Upload Size: 60 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: Australia/Sydney
	Debug Mode: Inactive

== Theme ==
	Name: Jtheme Jello Child
	Version: 1.0
	Author: Jezweb
	Child Theme: Yes
	Parent Theme Name: Jtheme Jello
	Parent Theme Version: 1.3.2
	Parent Theme Author: Jezweb

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.4
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.8
		Author: rocketgenius

	Mailgun
		Version: 1.7.1
		Author: Mailgun

	Members
		Version: 2.1.0
		Author: Justin Tadlock

	WooCommerce
		Version: 3.5.7
		Author: Automattic

	YITH WooCommerce Dynamic Pricing and Discounts Premium
		Version: 1.5.1
		Author: YITH


== Log ==
	: 
JS: showing 7 of 7JS: 2019-03-06 08:58:53 [error X 1][http://www.pokolbinestate.jezweb.sydney/wp-admin/post.php?post=2680&action=elementor:9:29] Cannot read property \'url\' of undefined 
JS: 2019-03-10 17:57:18 [error X 26][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.3:2:6882] Cannot read property \'select2\' of undefined 
JS: 2019-03-13 14:28:47 [error X 2][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.3:2:209245] Cannot read property \'prev\' of undefined 
JS: 2019-03-22 19:50:18 [error X 1][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13366\") has already been destroyed and cannot be used. 
JS: 2019-03-22 19:53:49 [error X 1][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view808\") has already been destroyed and cannot be used. 
JS: 2019-03-25 16:19:02 [error X 1][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4026\") has already been destroyed and cannot be used. 
JS: 2019-03-31 21:45:19 [error X 1][http://www.pokolbinestate.jezweb.sydney/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2050\") has already been destroyed and cannot be used. 

Log: showing 20 of 312019-04-04 05:33:23 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-04-04 05:33:23 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-04-04 05:33:25 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-04-04 05:33:25 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-04-04 05:33:25 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-04-04 05:33:25 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-04 05:33:26 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-04 05:33:27 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-04 05:33:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.4',
)]

PHP: showing 5 of 5PHP: 2019-03-14 01:55:15 [warning X 14][/home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::136] A non-numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-22 04:15:36 [notice X 3][/home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-23 06:26:30 [error X 6][/home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::273] Uncaught TypeError: Argument 1 passed to ElementorPro\Modules\QueryControl\Module::get_term_name_with_parents() must be an instance of WP_Term, array given, called in /home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php on line 114 and defined in /home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php:273
Stack trace:
#0 /home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(114): ElementorPro\Modules\QueryControl\Module->get_term_name_with_parents(Array)
#1 [internal function]: ElementorPro\Modules\QueryControl\Module->ajax_posts_filter_autocomplete(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home2/pokolbinestateco/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home2/pokolbinestateco/public_html/wp-includes/class-wp-hook.php(286): El [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-25 22:21:51 [notice X 2][/home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-custom-field.php::62] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-04 05:33:27 [warning X 1][/home2/pokolbinestateco/public_html/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::706] in_array() expects parameter 2 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>
![post-custom-field-missing-keys](https://user-images.githubusercontent.com/36604433/55745084-04cb2980-5a69-11e9-87d1-c4d0dedf067a.jpg)

**Comment by lucaskeiser** [comment]
I'm having a similar issue.

**Comment by cenemil** [comment]
Yeah, i thought it was fixed in the recent update but turns out the issue still exists up to now.

**Comment by alriksson** [comment]
+1 please add custom meta fields as well in the dynamic. So we can fetch it like crocoblocks dynamic widgets for images and text or whatever we want. Some external plugins utilize native Wordpress custom fields and we want to be able to fetch that data dynamically:
https://prnt.sc/nqsu75
https://prnt.sc/nqsug9

**Comment by shilo-ey** [comment]
Hi all!

After examining the reported issue, we couldn't reproduce it.

The behavior is:
1. While you have custom meta values stored in your custom field - the option to select your custom field will be available (in the dynamic menu). if you're creating a template - make sure that the preview content is one with the custom field filled in.
2. Make sure your meta key doesn't have an underscore (`_`) as a prefix (as it is hidden).

I've tested it with the following code (which works fine):

```PHP
function add_custom_box()
{
    $screens = ['post', 'my_cpt'];
    foreach ($screens as $screen) {
        add_meta_box(
            'my_box_id',           // ID
            'Custom Meta Box Title',  // Box title
            'my_custom_box_html',  // Content callback, must be of type callable
            $screen                   // the Post type
        );
    }
}
add_action('add_meta_boxes', 'add_custom_box');

function my_custom_box_html($post)
{
    ?>
    <label for="my_field">Description for this field</label>
    <input name="my_field" id="my_field" class="postbox" value="<?php echo esc_attr( get_post_meta( get_the_ID(), 'my_meta_key', true ) ); ?>">
    <?php
}

function save_postdata($post_id)
{
    if (array_key_exists('my_field', $_POST)) {
        update_post_meta(
            $post_id,
            'my_meta_key',
            $_POST['my_field']
        );
    }
}
add_action('save_post', 'save_postdata');
```

This way I was able to fetch the custom data dynamically.

Thanks.

**Comment by cenemil** [comment]
I apologize for the super delayed response. Yes, i figured it out by changing the Preview setting of the template to match the post/cpt entry that has the meta values set. Thanks for the input too @shilo-ey !

**Comment by xd1704** [comment]
Hi all,
i've installed a thrid part plug "Facebook event importer".
I'd like to join a Google map with lat/long stored in a custom field from them, that I don't find in the dynamic field.
@shilo-ey do I have to implement this code in the function.php ? (i'm quite new)
many thanks in advance,
xd1704

**Comment by cenemil** [comment]
Hello @xd1704,

I assume that plugin registers an event custom post type. It is essential to have a custom post type since that will connect the custom field to the dynamic field templating. Try clearing system cache or browser cache or follow these steps:

In your elementor template where you want the Google map to show, go to the template settings and look for the Preview option. Try assigning an existing event or item so it can pull real time data and don't forget to apply the changes. I'm not familiar with Google map in Anywhere elementor but does it really support dynamic fields assignment for both latitude and longitude?

**Comment by cenemil** [comment]
Ok, i just did a test in my local dev. The location field supports lat/long data.
